data:
  train_dir: ./dataset/split_ds/train
  val_dir: ./dataset/split_ds/val

training:
  batch_size: 32
  max_epochs: 30
  seed: 2000

model:
  learning_rate: 0.0005

checkpoint:
  path: ./saved_models/

experiment_name: animal_classification

mlflow:
   tracking_uri: http://localhost:5000
