data:
  root_dir: /media/smbanaru/9bf28602-242e-4916-960b-479e4c5d241e/datasets/SIDD_small_224x224_patches_v2/
  resume: False
  
training:
  net_type: DeVit
  batch_size: 64
  max_epochs: 32
  seed: 69
  num_workers: 12

model:
  learning_rate: 0.001

checkpoint:
  path: saved_models/
  filename: best_model-v4.ckpt

experiment_name: DeVit_SIDD_small_224_experiment_1

mlflow:
   tracking_uri: http://127.0.0.1:8083
   host: 127.0.0.1
   port: 8083