data:
  train_dir: /home/sbanaru/Desktop/DisNet/dataset/split_ds/train
  val_dir: /home/sbanaru/Desktop/DisNet/dataset/split_ds/val

training:
  batch_size: 32
  max_epochs: 2
  seed: 69

model:
  learning_rate: 0.001

checkpoint:
  path: saved_models/

experiment_name: animal_classification

mlflow:
   tracking_uri: http://localhost:5000